spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/master
          jwk-set-uri: http://localhost:8180/realms/master/protocol/openid-connect/certs
